# Generated by Django 5.2.1 on 2025-06-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_received', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('sds_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='contractors/ids/')),
                ('onboarded', models.BooleanField(default=False)),
                ('onboarding_date', models.DateField(auto_now_add=True)),
                ('certifications', models.ManyToManyField(blank=True, to='ohs.certification')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('certifications', models.ManyToManyField(blank=True, related_name='employees', to='ohs.certification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FLRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('identified_hazards', models.TextField()),
                ('control_measures', models.TextField()),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('risk_identified', models.TextField()),
                ('risk_level', models.CharField(max_length=50)),
                ('control_measures', models.TextField()),
                ('date_assessed', models.DateField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('location', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Near Miss', 'Near Miss'), ('First Aid', 'First Aid'), ('Medical Treatment', 'Medical Treatment'), ('Lost Time', 'Lost Time'), ('Fatality', 'Fatality')], max_length=50)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('hazards', models.TextField()),
                ('controls', models.TextField()),
                ('signed', models.BooleanField(default=False)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('SDS', 'Safety Data Sheet'), ('SOP', 'Standard Operating Procedure')], max_length=10)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohs.material')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('task', models.CharField(max_length=255)),
                ('observation_type', models.CharField(choices=[('PTO', 'Planned Task Observation'), ('CCV', 'Critical Control Verification')], max_length=10)),
                ('controls_verified', models.TextField()),
                ('findings', models.TextField()),
                ('follow_up_required', models.BooleanField(default=False)),
                ('observed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('ppe_inspection', models.BooleanField(default=False)),
                ('fire_safety_check', models.BooleanField(default=False)),
                ('equipment_condition', models.BooleanField(default=False)),
                ('emergency_exits_clear', models.BooleanField(default=False)),
                ('safety_signage_visible', models.BooleanField(default=False)),
                ('first_aid_kit_stocked', models.BooleanField(default=False)),
                ('housekeeping_checked', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
