# Generated by Django 5.2.1 on 2025-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohs', '0002_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='target',
            field=models.TextField(),
        ),
    ]
