# Generated by Django 5.2.1 on 2025-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohs', '0003_alter_objective_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='ohs.document'),
        ),
    ]
