# Generated by Django 5.2.1 on 2025-06-05 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohs', '0004_observation_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='observations/'),
        ),
        migrations.AddField(
            model_name='observation',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
