# Generated by Django 5.2.1 on 2025-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohs', '0005_observation_file_observation_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_file',
            field=models.FileField(blank=True, null=True, upload_to='contractors/files/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/files/'),
        ),
        migrations.AddField(
            model_name='flra',
            name='flra_file',
            field=models.FileField(blank=True, null=True, upload_to='flra/files/'),
        ),
        migrations.AddField(
            model_name='fra',
            name='fra_file',
            field=models.FileField(blank=True, null=True, upload_to='fra/files/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_file',
            field=models.FileField(blank=True, null=True, upload_to='incidents/files/'),
        ),
        migrations.AddField(
            model_name='jsa',
            name='jsa_file',
            field=models.FileField(blank=True, null=True, upload_to='jsa/files/'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/files/'),
        ),
        migrations.AddField(
            model_name='objective',
            name='objective_file',
            field=models.FileField(blank=True, null=True, upload_to='objectives/files/'),
        ),
        migrations.AddField(
            model_name='safetychecklist',
            name='checklist_file',
            field=models.FileField(blank=True, null=True, upload_to='checklists/files/'),
        ),
    ]
