# Generated by Django 5.2.1 on 2025-06-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohs', '0006_remove_observation_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.CreateModel(
            name='TrainingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='not started', max_length=20)),
                ('training_material', models.FileField(blank=True, null=True, upload_to='training/files/')),
                ('certificate_required', models.BooleanField(default=False)),
                ('certificate_upload', models.FileField(blank=True, null=True, upload_to='training/certificates/')),
                ('assigned_employees', models.ManyToManyField(related_name='trainings', to='ohs.employee')),
            ],
        ),
    ]
